// Generated by Selenium IDE

using System.Drawing;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;

[TestFixture]
public class HomeTabsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }

    [SetUp]
    public void SetUp()
    {
        var baseDir = AppDomain.CurrentDomain.BaseDirectory;
        driver = new ChromeDriver(baseDir);
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void tab()
    {
        driver.Navigate().GoToUrl("https://localhost:4200/");
        driver.Manage().Window.Size = new Size(1536, 824);
        Thread.Sleep(10000);
        driver.FindElement(By.LinkText("Home")).Click();
        {
            var element = driver.FindElement(By.LinkText("Home"));
            var builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Assert.AreEqual("https://localhost:4200/home", driver.Url);
        {
            var element = driver.FindElement(By.TagName("body"));
            var builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.LinkText("About us")).Click();
        Assert.AreEqual("https://localhost:4200/about", driver.Url);

        driver.FindElement(By.LinkText("Services")).Click();
        Assert.AreEqual("https://localhost:4200/services", driver.Url);

        driver.FindElement(By.LinkText("Doctors")).Click();
        Assert.AreEqual("https://localhost:4200/doctors", driver.Url);
    }
}