//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Profile.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не может быть пустым.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректый день.
        /// </summary>
        public static string NotCorrectDay {
            get {
                return ResourceManager.GetString("NotCorrectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный месяц.
        /// </summary>
        public static string NotCorrectMonth {
            get {
                return ResourceManager.GetString("NotCorrectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректный год.
        /// </summary>
        public static string NotCorrectYear {
            get {
                return ResourceManager.GetString("NotCorrectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с Id {0} не найлен.
        /// </summary>
        public static string NotFoundAccount {
            get {
                return ResourceManager.GetString("NotFoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктор не найден по Id {0}.
        /// </summary>
        public static string NotFoundDoctorById {
            get {
                return ResourceManager.GetString("NotFoundDoctorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офис с Id {0} не найден.
        /// </summary>
        public static string NotFoundOffice {
            get {
                return ResourceManager.GetString("NotFoundOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациент не найден по Id {0}.
        /// </summary>
        public static string NotFoundPatient {
            get {
                return ResourceManager.GetString("NotFoundPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор не найден по Id {0}.
        /// </summary>
        public static string NotFoundReceptionist {
            get {
                return ResourceManager.GetString("NotFoundReceptionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специалисяция с Id {0} не найдена.
        /// </summary>
        public static string NotFoundSpecialition {
            get {
                return ResourceManager.GetString("NotFoundSpecialition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус с Id {0} не найдена.
        /// </summary>
        public static string NotFoundStatus {
            get {
                return ResourceManager.GetString("NotFoundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} уже существует.
        /// </summary>
        public static string NotUniqueEmail {
            get {
                return ResourceManager.GetString("NotUniqueEmail", resourceCulture);
            }
        }
    }
}
